
/**
 * Represents a contract opportunity from SAM.gov.
 */
export interface SamGovOpportunity {
  /**
   * The unique identifier for the opportunity.
   */
  id: string;
  /**
   * The title or description of the opportunity.
   */
  title: string;
  /**
   * The NAICS code for the opportunity.
   */
  ncode: string;
  /**
   * The department issuing the opportunity.
   */
  department: string;
  /**
   * The subtier of the department.
   */
  subtier: string;
  /**
   * The specific office within the subtier.
   */
  office: string;
  /**
   * The location related to the opportunity.
   */
  location: {
    city?: { name: string; code?: string };
    state?: { name: string; code?: string };
    zip?: string;
    country?: { name: string; code?: string };
  } | null;
  /**
   * The closing date for the opportunity.
   */
  closingDate: string; // ISO date string
  /**
   * The type of opportunity (e.g., Solicitation, Sources Sought).
   */
  type: string;
  /**
   * Direct link to the opportunity on SAM.gov.
   */
  link: string;
  /**
   * Address of the office.
   */
  officeAddress: string;
  /**
   * Full description of the opportunity. This might be a URL or plain text.
   */
  description: string;
  /**
   * Attachments
   */
  resourceLinks: string[];
}

/**
 * Represents a summarized bid opportunity from SAM.gov, generated by AI.
 */
export interface BidSummary {
  critical_requirements_and_compliance_points: string[];
  issuing_agency_and_mission: string;
  key_contract_data: {
    NAICS_code: string;
    PSC_FSC_code: string;
    attachments_and_fars: string[];
    contract_type: string;
    contracting_officer_contact_info: {
      email: string;
      name: string;
      phone: string;
    };
    evaluation_criteria: string;
    product_or_service_description: string;
    quantity_units_delivery: string[];
    response_deadlines: string[];
    set_aside_type: string;
    solicitation_number: string;
    submission_method: string;
  };
  price_comparison_cost_optimization: {
    contract_vehicle_options: string;
    total_cost_breakdown: string[];
    unit_price_range: string;
  };
  product_service_breakdown: {
    Description: string;
    NSN: string;
    'Part Number': string; // Note: "Part Number" has a space, might need careful handling or renaming in code if possible
    compliance_certifications: string[];
    requested_item: string;
    specifications_standards: string[];
  };
  recommendations_and_next_steps: {
    next_steps: string[];
    not_viable_reasoning: string;
    recommended_supplier: string;
    summary: string[];
  };
  sourcing_logic: {
    commercial_equivalency: string;
    direct_source: string[];
  };
  suitable_suppliers: Array<{
    company: string;
    profile_link: string;
    reason: string;
    type: string;
  }>;
  summary_of_requirement: string;
}


/**
 * Represents a classified SEPTA listing.
 */
export interface ClassifiedSeptaListing {
  id: string;
  title: string;
  categories: string[];
  score: number; // A score indicating the relevance/match confidence
  summary: string; // A brief AI-generated summary of the listing
}

export interface EnhancedRfqWithAi {
  id: string; // ID of the original RFQ or listing
  enhancements: string[]; // Array of AI-generated enhancements (e.g., suggested products, questions)
  confidenceScore: number; // Confidence level of the AI enhancement
  timestamp: string; // ISO date string
  metadata?: any; // Optional field for additional AI-specific metadata
}

